all:
	rm -rf CoverageBuddy.app
	mkdir -p CoverageBuddy.app/MacOS
	cp Info.plist CoverageBuddy.app
	cp CoverageBuddy CoverageBuddy.app/MacOS/
	cp ../bin/Debug/CoverageBuddy.exe CoverageBuddy.app/MacOS/
