
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action OpenFileAction;
	
	private global::Gtk.Action QuitAction;
	
	private global::Gtk.Action asdasdAction;
	
	private global::Gtk.Action OpenCoverageFileAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar mainMenuBar;
	
	private global::Gtk.HPaned hpaned1;
	
	private global::Gtk.ScrolledWindow scrolledwindow1;
	
	private global::Gtk.TreeView coverageTreeView;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Label titleLabel;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView fileTextView;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
		w1.Add (this.FileAction, "idiaeresis");
		this.OpenFileAction = new global::Gtk.Action ("OpenFileAction", global::Mono.Unix.Catalog.GetString ("Open File…"), null, null);
		this.OpenFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open File…");
		w1.Add (this.OpenFileAction, null);
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction, "<Primary><Mod2>q");
		this.asdasdAction = new global::Gtk.Action ("asdasdAction", global::Mono.Unix.Catalog.GetString ("asdasd"), null, null);
		this.asdasdAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("asdasd");
		w1.Add (this.asdasdAction, null);
		this.OpenCoverageFileAction = new global::Gtk.Action ("OpenCoverageFileAction", global::Mono.Unix.Catalog.GetString ("_Open Coverage File…"), null, null);
		this.OpenCoverageFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open File…");
		w1.Add (this.OpenCoverageFileAction, "<Primary><Mod2>o");
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='mainMenuBar'/></ui>");
		this.mainMenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/mainMenuBar")));
		this.mainMenuBar.Name = "mainMenuBar";
		this.vbox1.Add (this.mainMenuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.mainMenuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 500;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		this.coverageTreeView = new global::Gtk.TreeView ();
		this.coverageTreeView.WidthRequest = 450;
		this.coverageTreeView.CanFocus = true;
		this.coverageTreeView.Name = "coverageTreeView";
		this.scrolledwindow1.Add (this.coverageTreeView);
		this.hpaned1.Add (this.scrolledwindow1);
		global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.scrolledwindow1]));
		w4.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.titleLabel = new global::Gtk.Label ();
		this.titleLabel.Name = "titleLabel";
		this.titleLabel.Xalign = 0F;
		this.vbox2.Add (this.titleLabel);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.titleLabel]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.fileTextView = new global::Gtk.TextView ();
		this.fileTextView.WidthRequest = 1024;
		this.fileTextView.HeightRequest = 764;
		this.fileTextView.CanFocus = true;
		this.fileTextView.Name = "fileTextView";
		this.fileTextView.Editable = false;
		this.fileTextView.CursorVisible = false;
		this.GtkScrolledWindow.Add (this.fileTextView);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
		w7.Position = 1;
		this.hpaned1.Add (this.vbox2);
		this.vbox1.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
		w9.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1513;
		this.DefaultHeight = 832;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.QuitAction.Activated += new global::System.EventHandler (this.OnQuit);
		this.OpenCoverageFileAction.Activated += new global::System.EventHandler (this.OnOpen);
	}
}
